### ISSUE TITLE
Clarification request about the algorithm used here vs the Unicode text segmentation guidelines

### ISSUE THREAD

**Issue by Ablu** [magiclen/words-count#2]
Hi!

First: Thanks for this handy crate!

I compared the results of this crate against what https://unicode.org/reports/tr29/#Word_Boundaries mandates and was surprised to find some differences. I then checked the algorithm used by your crate and realized that it is a more pragmatic approach.

I wonder whether this is done on purpose (in which case it might make sense to explain it in the README) or whether this is an oversight?

The https://crates.io/crates/unicode-segmentation crate seems to claim to do it the "official" way (Disclaimer: I do not claim that I fully checked every rule and confirmed that it is correct) and comes to the conclusion that the example from the documentation at https://crates.io/crates/words-count should be 18 words long.

What is your thought on this?

**Comment by magiclen** [comment]
This crate doesn't follow the rules in [Word Boundaries](https://unicode.org/reports/tr29/#Word_Boundaries).

In Chinese composition,  I believe Chinese punctuation marks need to be counted as words. That's why `Rust是由 Mozilla 主導開發的通用、編譯型程式語言。` counts 20 words (including `、` and `。`).  You can get the same result in LibreOffice Writer.

**Comment by magiclen** [comment]
Also, you can try `"a-good-word"`.

```rust
use unicode_segmentation::UnicodeSegmentation;

fn main() {
    let s = "a-good-word";

    println!("{:?}", words_count::count(s));

    println!("{:?}", s.unicode_words().collect::<Vec<&str>>());

    println!("{:?}", s.split_word_bounds().collect::<Vec<&str>>());
}
```

This crate tells you `a-good-word` is a word, while the `unicode_words` function in [`unicode-segmentation`](https://crates.io/crates/unicode-segmentation) returns `["a", "good", "word"]`.

In LibreOffice Writer, `a-good-word` is counted as one word.

**Comment by Ablu** [comment]
Thanks for the clarification! I can totally understand that sometimes a unicode standard may not exactly be what one would want. I have sent a suggestion how to potentially clarify this a bit more in the README :). It might make sense to reference https://crates.io/crates/unicode-segmentation, but I left it out for now and will leave that up to you!
